{'application': False,
 'author': 'Nedas Zilinskas',
 'auto_install': False,
 'category': 'Website',
 'contributors': 'Nedas Zilinskas',
 'currency': 'EUR',
 'data': ['views/res_partner.xml',
          'views/res_partner_hcategory.xml',
          'views/forum_forum.xml'],
 'demo': [],
 'depends': ['website_forum', 'partner_category_hierarchy'],
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'live_test_url': 'https://minilini.com/page/start/website_forum_visibility/11.0',
 'maintainer': 'Nedas Zilinskas',
 'name': 'Forum Visibility',
 'price': 20.0,
 'qweb': [],
 'summary': 'Forum Visibility by Partner Category',
 'support': 'nedas.zilinskas@gmail.com',
 'version': '11.0.1.0.0',
 'website': 'http://nedaszilinskas.com'}
